### ISSUE TITLE
initial conditions problems

### ISSUE THREAD

**Issue by Francyrad** [JingyaoDOU/SWIFT_share_public#3]
Dear @JingyaoDOU 

I wanted to unify 2 hdf5 files to make an impact initial conditions.

So, first of all, i created 2 planets and relaxed them, as you wrote.
I can read the planets both with swiftsimio and SPLASH, so, nothing wrong there.

These planets have fixed entropies enabled. 

So, i created a script to unify them and it seems to work, there are no errors. However, when i try to start the simulation with swiftsim, it says that in the file there are no entropies data (i'm running swiftsim with fixed entropy as you suggest). Also, i cannot read the file with splash "impossible to read the header".

Did i do something wrong? Maybe I didn't load and appended all the data necessaries to make a collision? I attach you the file. Please, let me know
-Francesco

```
import h5py
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import swiftsimio as sw
import unyt
import woma
from woma.misc import utils
from copy import copy

R_earth = 6.371e6  # m
M_earth = 5.972e24  # kg m^-3

#The Gravitational constant, it may be useful if you want to add some constraints
G = 6.67408e-11  # m^3 kg^-1 s^-2

def load_to_woma(snapshot):
    # Load
    data = sw.load(snapshot)
    box_mid = 0.5 * data.metadata.boxsize[0].to(unyt.m)
    data.gas.coordinates.convert_to_mks()
    pos = np.array(data.gas.coordinates - box_mid)
    data.gas.velocities.convert_to_mks()
    vel = np.array(data.gas.velocities)
    data.gas.smoothing_lengths.convert_to_mks()
    h = np.array(data.gas.smoothing_lengths)
    data.gas.masses.convert_to_mks()
    m = np.array(data.gas.masses)
    data.gas.densities.convert_to_mks()
    rho = np.array(data.gas.densities)
    data.gas.pressures.convert_to_mks()
    p = np.array(data.gas.pressures)
    data.gas.internal_energies.convert_to_mks()
    u = np.array(data.gas.internal_energies)
    matid = np.array(data.gas.material_ids)
    # pid     = np.array(data.gas.particle_ids)

    pos_centerM = np.sum(pos * m[:, np.newaxis], axis=0) / np.sum(m)
    vel_centerM = np.sum(vel * m[:, np.newaxis], axis=0) / np.sum(m)

    pos -= pos_centerM
    vel -= vel_centerM

    pos_noatmo = pos[matid != 200]

    xy = np.hypot(pos_noatmo[:, 0], pos_noatmo[:, 1])
    r = np.hypot(xy, pos_noatmo[:, 2])
    r = np.sort(r)
    R = np.mean(r[-1000:])

    return pos, vel, h, m, rho, p, u, matid, R
    
    
    
loc_tar = "Rufu_2017_target_1kk_1000.hdf5"
loc_imp = "Rufu_2017_impactor_1kk_0100.hdf5"

pos_tar, vel_tar, h_tar, m_tar, rho_tar, p_tar, u_tar, matid_tar, R_tar = load_to_woma(
    loc_tar)
    
pos_imp, vel_imp, h_imp, m_imp, rho_imp, p_imp, u_imp, matid_imp, R_imp = load_to_woma(
    loc_imp)

M_t = np.sum(m_tar)
M_i = np.sum(m_imp)
R_t = R_tar
R_i = R_imp


# Mutual escape speed
#v_esc = np.sqrt(2 * G * (M_target + M_impactor) / (R_target + R_impactor))

# Initial position and velocity of the target
A1_pos_t = np.array([0.0, 0.0, 0.0])
A1_vel_t = np.array([0.0, 0.0, 0.0])





A1_pos_i, A1_vel_i = woma.impact_pos_vel_b_v_c_r(
    #    b       = np.sin(45 * np.pi/180),
    b=0.7,
    v_c=20500,
    #t=3600,  # seconds. If you want time, you need to setup b_v_c_t.
    r=4*R_earth,
    R_t=R_t,
    R_i=R_i,
    M_t=M_t,
    M_i=M_i,
    #units_v_c="v_esc",
    #units_b="B"
    #b : float The impact parameter b=sin(B), or the impact angle B if units_b is "B".
)

A1_pos_com = (M_t * A1_pos_t + M_i * A1_pos_i) / (M_t + M_i)
A1_pos_t -= A1_pos_com
A1_pos_i -= A1_pos_com

# Centre of momentum
A1_vel_com = (M_t * A1_vel_t + M_i * A1_vel_i) / (M_t + M_i)
A1_vel_t -= A1_vel_com
A1_vel_i -= A1_vel_com

pos_tar += A1_pos_t
vel_tar[:] += A1_vel_t

pos_imp += A1_pos_i
vel_imp[:] += A1_vel_i
print("Number of particles in target %d" % (len(pos_tar)))


print(A1_pos_t / R_earth, "R_earth")
print(A1_vel_t, "m/s")
print(A1_pos_i / R_earth, "R_earth")
print(A1_vel_i, "m/s")



with h5py.File(
    "Rufu_est_momentum_1kk.hdf5", "w"
) as f:
    woma.save_particle_data(
        f,
        np.append(pos_tar, pos_imp, axis=0),
        np.append(vel_tar, vel_imp, axis=0),
        np.append(m_tar, m_imp),
        np.append(h_tar, h_imp),
        np.append(rho_tar, rho_imp),
        np.append(p_tar, p_imp),
        np.append(u_tar, u_imp),
        np.append(matid_tar, matid_imp),
        boxsize=100000 * R_earth,
        file_to_SI=woma.Conversions(M_earth, R_earth, 1),
    )
```

**Comment by JingyaoDOU** [comment]
Hi Francesco,

Sorry for the late reply, I just came back to school and now everything should come normal.

In order to run the impact simulation, you don't need entropy forcing anymore. So you should compile a swift executable WITHOUT "--enable-planetary-fixed-entropy". You will normally have two versions of SWIFT executable, e.g. "swift"( configured normally without enabling fixed entropy) and "swift_EF"(configured with entropy forcing enabled)

The common process should be:
* step 1: cool target and impactor planets using "swift_EF" for 5-10 hours (simulation time). 
* step 2: continue cooling the planets after step 1 with normal "swift" for 5 hours. (using the snapshot finished from step 1 as the initial condition and running without entropy forcing).
* step 3: check the planet relaxed from step 2, to see if it fits the density, pressure, and temperature profiles.
* step 4: combine the target and impactor snapshot to generate an impact initial condition file.
* step 5: run simulation with "swift". (entropy forcing is only in the cooling process, impact simulation does not need it)

Please let me know if you have any other problems.

**Comment by Francyrad** [comment]
It worked, also the cooling process make sense: First you relax the planet with a fixed entropy, then you cool it.

Thank you again!
